// Hytale block definitions with colors for visualization
export interface HytaleBlock {
  name: string;
  category: string;
  color: string; // HSL color for visualization
}

export const HYTALE_BLOCKS: HytaleBlock[] = [
  // === NATURE / TERRAIN ===
  { name: "Soil_Grass", category: "Nature", color: "120 50% 40%" },
  { name: "Soil_Grass_Dry", category: "Nature", color: "45 40% 45%" },
  { name: "Soil_Grass_Jungle", category: "Nature", color: "140 60% 35%" },
  { name: "Soil_Grass_Boreal", category: "Nature", color: "160 30% 35%" },
  { name: "Soil", category: "Nature", color: "30 40% 30%" },
  { name: "Soil_Dry", category: "Nature", color: "35 35% 40%" },
  { name: "Soil_Rich", category: "Nature", color: "25 50% 20%" },
  { name: "Sand", category: "Nature", color: "45 60% 70%" },
  { name: "Sand_Red", category: "Nature", color: "15 50% 55%" },
  { name: "Sand_Black", category: "Nature", color: "0 0% 20%" },
  { name: "Gravel", category: "Nature", color: "0 0% 50%" },
  { name: "Gravel_Dark", category: "Nature", color: "0 0% 35%" },
  { name: "Clay", category: "Nature", color: "20 30% 55%" },
  { name: "Clay_Red", category: "Nature", color: "10 40% 45%" },
  { name: "Clay_White", category: "Nature", color: "30 15% 80%" },
  { name: "Mud", category: "Nature", color: "25 35% 25%" },
  { name: "Peat", category: "Nature", color: "30 30% 20%" },
  { name: "Snow", category: "Nature", color: "200 20% 95%" },
  { name: "Ice", category: "Nature", color: "200 60% 85%" },
  { name: "Ice_Packed", category: "Nature", color: "200 50% 75%" },
  { name: "Permafrost", category: "Nature", color: "200 15% 60%" },
  
  // === STONE TYPES ===
  { name: "Stone", category: "Stone", color: "0 0% 55%" },
  { name: "Stone_Cobble", category: "Stone", color: "0 0% 45%" },
  { name: "Stone_Brick", category: "Stone", color: "0 0% 60%" },
  { name: "Stone_Mossy", category: "Stone", color: "120 20% 45%" },
  { name: "Stone_Cracked", category: "Stone", color: "0 0% 48%" },
  { name: "Stone_Polished", category: "Stone", color: "0 0% 65%" },
  { name: "Granite", category: "Stone", color: "15 25% 45%" },
  { name: "Granite_Polished", category: "Stone", color: "15 20% 55%" },
  { name: "Marble", category: "Stone", color: "0 0% 90%" },
  { name: "Marble_Black", category: "Stone", color: "0 0% 15%" },
  { name: "Slate", category: "Stone", color: "220 10% 35%" },
  { name: "Basalt", category: "Stone", color: "0 0% 25%" },
  { name: "Obsidian", category: "Stone", color: "280 30% 15%" },
  { name: "Sandstone", category: "Stone", color: "40 50% 65%" },
  { name: "Sandstone_Red", category: "Stone", color: "15 55% 50%" },
  { name: "Limestone", category: "Stone", color: "45 20% 75%" },
  { name: "Dolomite", category: "Stone", color: "30 15% 70%" },
  { name: "Andesite", category: "Stone", color: "0 0% 40%" },
  { name: "Diorite", category: "Stone", color: "0 0% 70%" },
  { name: "Tuff", category: "Stone", color: "80 10% 50%" },
  
  // === WOOD TYPES ===
  { name: "Wood_Oak", category: "Wood", color: "30 50% 35%" },
  { name: "Wood_Oak_Log", category: "Wood", color: "25 40% 30%" },
  { name: "Wood_Birch", category: "Wood", color: "40 30% 70%" },
  { name: "Wood_Birch_Log", category: "Wood", color: "45 20% 85%" },
  { name: "Wood_Spruce", category: "Wood", color: "25 40% 25%" },
  { name: "Wood_Spruce_Log", category: "Wood", color: "20 35% 22%" },
  { name: "Wood_Jungle", category: "Wood", color: "35 45% 30%" },
  { name: "Wood_Jungle_Log", category: "Wood", color: "30 40% 28%" },
  { name: "Wood_Acacia", category: "Wood", color: "20 60% 45%" },
  { name: "Wood_Acacia_Log", category: "Wood", color: "25 50% 35%" },
  { name: "Wood_Dark_Oak", category: "Wood", color: "25 40% 20%" },
  { name: "Wood_Dark_Oak_Log", category: "Wood", color: "20 35% 18%" },
  { name: "Wood_Cherry", category: "Wood", color: "350 40% 50%" },
  { name: "Wood_Cherry_Log", category: "Wood", color: "25 30% 40%" },
  { name: "Wood_Mangrove", category: "Wood", color: "15 45% 35%" },
  { name: "Wood_Planks_Oak", category: "Wood", color: "35 45% 45%" },
  { name: "Wood_Planks_Birch", category: "Wood", color: "45 35% 75%" },
  { name: "Wood_Planks_Spruce", category: "Wood", color: "30 35% 30%" },
  { name: "Wood_Planks_Jungle", category: "Wood", color: "30 40% 40%" },
  { name: "Wood_Planks_Acacia", category: "Wood", color: "25 55% 50%" },
  { name: "Wood_Planks_Dark_Oak", category: "Wood", color: "25 35% 25%" },
  { name: "Wood_Planks_Cherry", category: "Wood", color: "350 35% 55%" },
  
  // === METALS & ORES ===
  { name: "Iron_Ore", category: "Metals", color: "25 20% 50%" },
  { name: "Gold_Ore", category: "Metals", color: "45 80% 50%" },
  { name: "Copper_Ore", category: "Metals", color: "25 70% 45%" },
  { name: "Silver_Ore", category: "Metals", color: "0 0% 75%" },
  { name: "Coal_Ore", category: "Metals", color: "0 0% 20%" },
  { name: "Cobalt_Ore", category: "Metals", color: "220 70% 45%" },
  { name: "Mythril_Ore", category: "Metals", color: "180 60% 55%" },
  { name: "Adamantite_Ore", category: "Metals", color: "340 70% 40%" },
  { name: "Iron_Block", category: "Metals", color: "0 0% 75%" },
  { name: "Gold_Block", category: "Metals", color: "45 90% 55%" },
  { name: "Copper_Block", category: "Metals", color: "25 80% 55%" },
  { name: "Silver_Block", category: "Metals", color: "0 0% 85%" },
  { name: "Cobalt_Block", category: "Metals", color: "220 80% 55%" },
  { name: "Mythril_Block", category: "Metals", color: "180 70% 60%" },
  { name: "Adamantite_Block", category: "Metals", color: "340 80% 50%" },
  
  // === GEMS & CRYSTALS ===
  { name: "Diamond_Ore", category: "Gems", color: "180 80% 70%" },
  { name: "Ruby_Ore", category: "Gems", color: "350 80% 45%" },
  { name: "Sapphire_Ore", category: "Gems", color: "220 80% 50%" },
  { name: "Emerald_Ore", category: "Gems", color: "140 80% 45%" },
  { name: "Amethyst_Ore", category: "Gems", color: "280 60% 55%" },
  { name: "Topaz_Ore", category: "Gems", color: "35 80% 55%" },
  { name: "Diamond_Block", category: "Gems", color: "180 90% 75%" },
  { name: "Ruby_Block", category: "Gems", color: "350 90% 50%" },
  { name: "Sapphire_Block", category: "Gems", color: "220 90% 55%" },
  { name: "Emerald_Block", category: "Gems", color: "140 90% 50%" },
  { name: "Amethyst_Block", category: "Gems", color: "280 70% 60%" },
  { name: "Crystal_Blue", category: "Gems", color: "200 80% 60%" },
  { name: "Crystal_Red", category: "Gems", color: "0 80% 50%" },
  { name: "Crystal_Green", category: "Gems", color: "140 70% 45%" },
  { name: "Crystal_Purple", category: "Gems", color: "280 70% 55%" },
  { name: "Crystal_White", category: "Gems", color: "0 0% 90%" },
  
  // === GLASS ===
  { name: "Glass", category: "Glass", color: "200 50% 85%" },
  { name: "Glass_White", category: "Glass", color: "0 0% 95%" },
  { name: "Glass_Red", category: "Glass", color: "0 70% 50%" },
  { name: "Glass_Orange", category: "Glass", color: "30 80% 55%" },
  { name: "Glass_Yellow", category: "Glass", color: "50 80% 60%" },
  { name: "Glass_Green", category: "Glass", color: "120 60% 45%" },
  { name: "Glass_Blue", category: "Glass", color: "210 70% 55%" },
  { name: "Glass_Purple", category: "Glass", color: "280 60% 50%" },
  { name: "Glass_Pink", category: "Glass", color: "330 60% 65%" },
  { name: "Glass_Black", category: "Glass", color: "0 0% 15%" },
  { name: "Glass_Tinted", category: "Glass", color: "270 30% 50%" },
  
  // === BUILDING MATERIALS ===
  { name: "Brick_Red", category: "Building", color: "0 60% 45%" },
  { name: "Brick_Brown", category: "Building", color: "25 40% 40%" },
  { name: "Brick_White", category: "Building", color: "0 0% 85%" },
  { name: "Brick_Black", category: "Building", color: "0 0% 20%" },
  { name: "Brick_Stone", category: "Building", color: "0 0% 55%" },
  { name: "Concrete", category: "Building", color: "0 0% 65%" },
  { name: "Concrete_White", category: "Building", color: "0 0% 90%" },
  { name: "Concrete_Black", category: "Building", color: "0 0% 15%" },
  { name: "Concrete_Red", category: "Building", color: "0 50% 45%" },
  { name: "Concrete_Orange", category: "Building", color: "25 60% 50%" },
  { name: "Concrete_Yellow", category: "Building", color: "50 70% 55%" },
  { name: "Concrete_Green", category: "Building", color: "120 45% 40%" },
  { name: "Concrete_Blue", category: "Building", color: "210 55% 45%" },
  { name: "Concrete_Purple", category: "Building", color: "280 50% 45%" },
  { name: "Terracotta", category: "Building", color: "20 50% 50%" },
  { name: "Terracotta_Glazed_White", category: "Building", color: "0 0% 85%" },
  { name: "Terracotta_Glazed_Red", category: "Building", color: "0 65% 50%" },
  { name: "Terracotta_Glazed_Blue", category: "Building", color: "210 65% 50%" },
  { name: "Terracotta_Glazed_Green", category: "Building", color: "140 55% 45%" },
  { name: "Thatch", category: "Building", color: "45 50% 55%" },
  { name: "Thatch_Dark", category: "Building", color: "40 45% 40%" },
  { name: "Tile_Roof_Red", category: "Building", color: "10 55% 45%" },
  { name: "Tile_Roof_Blue", category: "Building", color: "210 50% 45%" },
  { name: "Tile_Roof_Green", category: "Building", color: "140 45% 40%" },
  { name: "Tile_Floor_White", category: "Building", color: "0 0% 90%" },
  { name: "Tile_Floor_Black", category: "Building", color: "0 0% 15%" },
  { name: "Tile_Floor_Checker", category: "Building", color: "0 0% 60%" },
  
  // === DECORATION ===
  { name: "Wool_White", category: "Decoration", color: "0 0% 95%" },
  { name: "Wool_Black", category: "Decoration", color: "0 0% 15%" },
  { name: "Wool_Red", category: "Decoration", color: "0 70% 50%" },
  { name: "Wool_Orange", category: "Decoration", color: "30 80% 55%" },
  { name: "Wool_Yellow", category: "Decoration", color: "50 80% 60%" },
  { name: "Wool_Green", category: "Decoration", color: "120 55% 45%" },
  { name: "Wool_Blue", category: "Decoration", color: "210 65% 50%" },
  { name: "Wool_Purple", category: "Decoration", color: "280 55% 50%" },
  { name: "Wool_Pink", category: "Decoration", color: "330 60% 70%" },
  { name: "Wool_Brown", category: "Decoration", color: "30 45% 35%" },
  { name: "Wool_Gray", category: "Decoration", color: "0 0% 50%" },
  { name: "Carpet_Ornate", category: "Decoration", color: "350 60% 40%" },
  { name: "Hay_Bale", category: "Decoration", color: "50 60% 55%" },
  { name: "Bookshelf", category: "Decoration", color: "25 40% 35%" },
  { name: "Barrel", category: "Decoration", color: "30 45% 40%" },
  { name: "Crate", category: "Decoration", color: "35 40% 45%" },
  
  // === PLANTS & FOLIAGE ===
  { name: "Leaves_Oak", category: "Plants", color: "120 50% 35%" },
  { name: "Leaves_Birch", category: "Plants", color: "90 45% 45%" },
  { name: "Leaves_Spruce", category: "Plants", color: "150 40% 25%" },
  { name: "Leaves_Jungle", category: "Plants", color: "130 55% 30%" },
  { name: "Leaves_Acacia", category: "Plants", color: "80 45% 40%" },
  { name: "Leaves_Cherry", category: "Plants", color: "340 50% 65%" },
  { name: "Leaves_Autumn_Red", category: "Plants", color: "15 70% 45%" },
  { name: "Leaves_Autumn_Orange", category: "Plants", color: "30 75% 50%" },
  { name: "Leaves_Autumn_Yellow", category: "Plants", color: "50 70% 55%" },
  { name: "Moss", category: "Plants", color: "120 40% 35%" },
  { name: "Vines", category: "Plants", color: "130 45% 30%" },
  { name: "Mushroom_Red", category: "Plants", color: "0 70% 45%" },
  { name: "Mushroom_Brown", category: "Plants", color: "30 40% 35%" },
  { name: "Cactus", category: "Plants", color: "120 50% 40%" },
  { name: "Bamboo", category: "Plants", color: "80 55% 45%" },
  
  // === SPECIAL / MAGICAL ===
  { name: "Water", category: "Special", color: "210 80% 50%" },
  { name: "Water_Deep", category: "Special", color: "220 75% 35%" },
  { name: "Lava", category: "Special", color: "15 100% 50%" },
  { name: "Void", category: "Special", color: "280 80% 20%" },
  { name: "Light", category: "Special", color: "50 100% 75%" },
  { name: "Glow_Stone", category: "Special", color: "45 80% 65%" },
  { name: "Ender_Stone", category: "Special", color: "280 40% 30%" },
  { name: "Portal_Block", category: "Special", color: "270 90% 45%" },
  { name: "Soul_Stone", category: "Special", color: "200 60% 35%" },
  { name: "Cursed_Stone", category: "Special", color: "320 60% 25%" },
  { name: "Blessed_Stone", category: "Special", color: "45 60% 70%" },
  { name: "Arcane_Block", category: "Special", color: "260 70% 50%" },
  { name: "Runic_Stone", category: "Special", color: "220 50% 45%" },
  
  // === DUNGEON / ANCIENT ===
  { name: "Dungeon_Brick", category: "Dungeon", color: "0 0% 30%" },
  { name: "Dungeon_Brick_Mossy", category: "Dungeon", color: "120 25% 30%" },
  { name: "Dungeon_Brick_Cracked", category: "Dungeon", color: "0 0% 28%" },
  { name: "Ancient_Stone", category: "Dungeon", color: "35 15% 40%" },
  { name: "Ancient_Brick", category: "Dungeon", color: "30 20% 35%" },
  { name: "Tomb_Stone", category: "Dungeon", color: "0 0% 35%" },
  { name: "Sarcophagus", category: "Dungeon", color: "45 25% 50%" },
  { name: "Bone_Block", category: "Dungeon", color: "40 20% 80%" },
  { name: "Skull_Pile", category: "Dungeon", color: "35 15% 75%" },
  { name: "Chain_Block", category: "Dungeon", color: "0 0% 40%" },
  { name: "Cage", category: "Dungeon", color: "25 15% 30%" },
  { name: "Cobweb", category: "Dungeon", color: "0 0% 90%" },
  
  // === NETHER / INFERNAL ===
  { name: "Netherrack", category: "Nether", color: "0 50% 30%" },
  { name: "Nether_Brick", category: "Nether", color: "350 40% 25%" },
  { name: "Soul_Sand", category: "Nether", color: "30 25% 30%" },
  { name: "Magma_Block", category: "Nether", color: "20 90% 40%" },
  { name: "Blackite", category: "Nether", color: "0 0% 10%" },
  { name: "Crimson_Wood", category: "Nether", color: "340 50% 35%" },
  { name: "Warped_Wood", category: "Nether", color: "170 50% 35%" },
  { name: "Shroomlight", category: "Nether", color: "35 80% 60%" },
  { name: "Glowshroom", category: "Nether", color: "180 60% 50%" },
  
  // === TECH / MECHANICAL ===
  { name: "Machine_Block", category: "Tech", color: "0 0% 50%" },
  { name: "Gear_Block", category: "Tech", color: "25 20% 45%" },
  { name: "Pipe_Block", category: "Tech", color: "0 0% 55%" },
  { name: "Vent", category: "Tech", color: "0 0% 40%" },
  { name: "Wire_Block", category: "Tech", color: "40 70% 50%" },
  { name: "Lamp_Block", category: "Tech", color: "50 90% 70%" },
  { name: "Redstone_Block", category: "Tech", color: "0 80% 45%" },
  { name: "Piston", category: "Tech", color: "30 30% 45%" },
  
  // === ZONE SPECIFIC ===
  { name: "Zone1_Emerald_Grove_Stone", category: "Zones", color: "140 40% 45%" },
  { name: "Zone2_Howling_Sands_Stone", category: "Zones", color: "40 50% 55%" },
  { name: "Zone3_Borea_Ice", category: "Zones", color: "200 70% 80%" },
  { name: "Zone4_Devastated_Lands_Rock", category: "Zones", color: "0 30% 25%" },
];

export const BLOCK_CATEGORIES = [...new Set(HYTALE_BLOCKS.map(b => b.category))];

export function getBlockByName(name: string): HytaleBlock | undefined {
  return HYTALE_BLOCKS.find(b => b.name === name);
}

export function getBlockColor(name: string): string {
  const block = getBlockByName(name);
  return block?.color || "0 0% 50%";
}
